### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by ai** [mbalabash/estimo#1]
When I am calling

```js
      let perf = await estimo(output)
```

I got an error:

```js
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./node_modules/.bin/perf-timeline ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:253:12)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

`output` contains something like `/tmp/size-limit-1555468039103/index.js`.

Maybe it happens because current working dir is `/Dev/size-limit/test/fixtures/bad` and `node_modules` are in `/Dev/size-limit/`.

You should call `npx perf-timeline` instead of `./node_modules/.bin/perf-timeline`.

**Comment by mbalabash** [comment]
Now i got an error:
```
Error: spawn npx perf-timeline ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:253:12)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by mbalabash** [comment]
Seems like spawn process can work with npx.
I change `npx` on [node-npx](https://github.com/saltyshiomix/node-npx).

**Comment by mbalabash** [comment]
I can't release new version right now. Will do it in next 3 hours.

**Comment by mbalabash** [comment]
Fixed in v0.1.6 and released on npm

**Comment by ai** [comment]
Got new error:

```
{ Error: spawn perf-timeline ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn perf-timeline',
  path: 'perf-timeline',
  spawnargs:
   [ 'generate',
     'file:///home/ai/Dev/size-limit/node_modules/estimo/temp/rgpTC-Rq5jG7eQiXSSPbd.html',
     '--path',
     '/home/ai/Dev/size-limit/node_modules/estimo/temp/qHIYW2gH9Ev8_9bf2VrUf.json' ] }
```

**Comment by mbalabash** [comment]
Strange. Can't reproduce.
Which OS you are use?

**Comment by ai** [comment]
Linux. npm packages installed locally. Also, I am running test in:

```
package.json
test/
  fixtures/
    bad/
      package.json
      index.js
```

Maybe this double `package.json` creates a problem?

**Comment by mbalabash** [comment]
Are you sure you using 0.1.6 version?

**Comment by ai** [comment]
Yeap. I had different error on previous version.

**Comment by mbalabash** [comment]
OK. I will try to reproduce with your project structure and double `package.json` cause.

**Comment by mbalabash** [comment]
Yeap

**Comment by mbalabash** [comment]
If you run from directory where node_modules are exist, but doesn't have lib. It throws an error.

**Comment by mbalabash** [comment]
Normal `npx` behavior in this case is try to fetch lib and run it. But it also throws the same error.

**Comment by mbalabash** [comment]
Seems like problem with how `npx` works. 
If you try `npx estimo ...`. The npx will fetch and run estimo. But inside the estimo we run `perf-timeline` by `npx`. My assumption is they can't synchronize with themselves and locate libs.

When we have required libs in `node_modules`. `Npx` just take it from there.

**Comment by ai** [comment]
Maybe we can walk through current directories (`/a/b/c`, `/a/b`, `/a`, `/`) to find the right place with `./node_modules/.bin/perf-timeline`?

**Comment by ai** [comment]
Of course, we should start from `process.cwd()` and call `path.dirname` until we will be on the root.

**Comment by mbalabash** [comment]
Yes. I think we can combine recursive function, `process.cwd()`, `path.join`, `fs.exists` to try to find `perf-timeline`.

It is block you? 
I can try to do it tomorrow.

**Comment by mbalabash** [comment]
I added `findPerfTimelineTool` function to locate `perf-timeline` lib.
Seems to me like it works. Can you install estimo from latest `master` and check it?

**Comment by ai** [comment]
`master` works perfectly :+1: I got 17 seconds for 30 KB gzipped file.

Is it seconds or milliseconds?

**Comment by mbalabash** [comment]
Nice.
Can you provide output? I'm not sure where you saw it.

**Comment by ai** [comment]
```js
// index.js
require('chalk')
require('redux')
require('memory-fs')
```

```js
{ start: 0,
  end: 36.91799999773502,
  duration: 36.91799999773502,
  parseHTML: 0.7819999999999967,
  javaScript: 16.235,
  javaScriptCompile: 4.072000000000003,
  styles: 0.1490000000000009,
  updateLayerTree: 0.126,
  layout: 0.08899999999999864,
  paint: 0.032,
  raster: 0,
  composite: 0.036000000000001364,
  extendedInfo:
   { domContentLoaded: 35.08899999782443,
     loadTime: 34.83399999886751,
     firstPaint: 0,
     javaScript: {} },
  title: 'Load',
  type: 'Load' }
```

**Comment by mbalabash** [comment]
It is a milliseconds.

**Comment by ai** [comment]
:+1: I will use `exec = (perf.javaScript + perf.javaScriptCompile) / 1000` in Size Limit

**Comment by mbalabash** [comment]
Yeap. 
I do the same in examples.
`0.1.7` was released to npm.

**Comment by ai** [comment]
Fond new problem

```
/home/ai/my-js-lib/
  node_modules/
    size-limit/
      node_modules/
        .bin/
          perf-timeline
```

```sh
/home/ai/my-js-lib ➤ npx size-limit
Error: Can't find perf-timeline module!
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:52:11)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at Promise (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:7:30)
    at new Promise (<anonymous>)
    at spawnTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:5:10)
    at generateChromeTimelines (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:23:11)
    at estimo (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/index.js:64:29)
```

**Comment by mbalabash** [comment]
Does `npx size-limit --no-install` will work? From same dir.

**Comment by ai** [comment]
@mbalabash 

```
my-js-lib
➤ npx size-limit --no-install
Error: Can't find perf-timeline module!
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:52:11)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at Promise (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:7:30)
    at new Promise (<anonymous>)
    at spawnTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:5:10)
    at generateChromeTimelines (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:23:11)
    at estimo (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/index.js:64:29)
                                                                                
my-js-lib
➤ npx size-limit --ignore-existing
Error: Can't find perf-timeline module!
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:52:11)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at Promise (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:7:30)
    at new Promise (<anonymous>)
    at spawnTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:5:10)
    at generateChromeTimelines (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:23:11)
    at estimo (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/index.js:64:29)
                                                                                
my-js-lib
➤ ./node_modules/.bin/size-limit 
Error: Can't find perf-timeline module!
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:52:11)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at findPerfTimelineTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/utils.js:60:10)
    at Promise (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:7:30)
    at new Promise (<anonymous>)
    at spawnTool (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:5:10)
    at generateChromeTimelines (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/perfTimelineCliAdapter.js:23:11)
    at estimo (/home/ai/Dev/my-js-lib/node_modules/size-limit/node_modules/estimo/src/index.js:64:29)
```

**Comment by ai** [comment]
`estimo` is inside `size-limit`’s `node_modules`:

```


/home/ai/my-js-lib/
  node_modules/
    size-limit/
      node_modules/
        estimo
        .bin/
          perf-timeline
```

**Comment by mbalabash** [comment]
Looks like another issue with how ‘npx’ works 😐.
I will reproduce this case and will work on it.

**Comment by ai** [comment]
Should we have connection with `npx` behavior? As I remember we are looking for binary manually.

**Comment by mbalabash** [comment]
Wait
Without npx you also getting this error?

**Comment by ai** [comment]
Yeap, it doesn't work even without `npx`

**Comment by mbalabash** [comment]
Sory, miss click from mobile phone 😅

**Comment by mbalabash** [comment]
OK
Now i will test this case and give you updates.

**Comment by mbalabash** [comment]
```
/home/ai/my-js-lib/
  node_modules/
    size-limit/
      node_modules/
        estimo
        .bin/
          perf-timeline
```
In this case `cwd()` will be `my-js-lib`. 
Our method `findPerfTimelineTool` searching in current directory and go up to root directory.

But for handle this case. `findPerfTimelineTool` should go deeper if it didn't found lib in current or upper directories.

**Comment by ai** [comment]
You can use `__dirname` of `estimo` file and go back to root from it.

`cwd` will never be inside `node_modules`.

**Comment by mbalabash** [comment]
Seems like need to change one line from `-findPerfTimelineTool(process.cwd())` to `+findPerfTimelineTool(__dirname)`

**Comment by mbalabash** [comment]
It works on my reproduction for your case. Can you test from latest `master`?

**Comment by mbalabash** [comment]
It works on my reproduction for your case.
Can you test from latest `master`?

**Comment by ai** [comment]
Perfect:

```sh
➤ npx size-limit

  Time limit:   500 ms
  Package size: 0 B    with all dependencies, minified and gzipped
  Loading time: 0 ms   on slow 3G
  Running time: 76 ms  on Snapdragon 410
  Total time:   76 ms
```

**Comment by mbalabash** [comment]
Great work!

**Comment by mbalabash** [comment]
`v0.1.9` was released to npm
